include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - '**.g.dart'
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    - public_member_api_docs
    - await_only_futures