name: translit
description: Simple dart package for converting Cyrillic symbols to Translit and back
version: 2.0.1

homepage: https://github.com/alexeynobody/translit-dart

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  test: ^1.16.4
  flutter_lints: ^2.0.1