name: Test

on:
  push:
    branches:
      - '*'
      - '*/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Install Dart'
        uses: dart-lang/setup-dart@v0.3
        with:
          sdk: beta

      - name: 'Pub get'
        run: dart pub get

      - name: 'Analyze'
        run: dart analyze

      - name: 'Test'
        run: dart test
